version: "3.9"

services:
  miner:
    image: ghcr.io/armoniax/amnod:1.0.4
    container_name: miner
    working_dir: /miner
    entrypoint: ["./bin/start.sh", "--disable-replay-opts --enable-account-queries=true --snapshot ./latest.bin"]
    # entrypoint: ["./bin/start.sh", "--disable-replay-opts --enable-account-queries=true"]
    restart: always
    privileged: true
    ports:
      - "8080:8888"
      - "9806:9876"
      - "9555:9555"
    volumes:
      - ./:/miner
    dns:
      - 114.114.114.114
      - 8.8.8.8

networks:
  default:
    name: amax
    external: true
